cdn:  #静态文件与主站用的，例如填写https://aa.com/ 注意末尾要加上/ 以下各种链接都会加上这个前缀，注意字体文件跨域问题。
favicon: https://files.seeusercontent.com/2026/03/16/xoG7/favicon.ico
headerbg: headerbg/12.html #头部背景特效,内置13个特效,可以直接访问headerbg/*.html 查看

icoapi:
  enable: false #开启后，数据文件里的ICO失效。
  url: 'https://t3.gstatic.cn/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&size=256&url=' # 填写ICO API的URL

ctr:  #通过第三方统计服务，统计网址点击频次
  enable: false #开启后，使用/go/?url= 跳转，需要输入命令hexo new page go 创建页面
  code: '<script> var _hmt = _hmt || [];(function() {var hm = document.createElement("script");hm.src = "https://hm.baidu.com/hm.js?062685e39e06f9947b865df2e13901f7";var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hm, s);})();</script>' # 填写第三方统计代码，要求能显示详细受访页面。

lytoday:
  enable: false #启用今日热榜功能，该接口每天免费访问次数为500次。
  url: https://lytoday.lylme.com/?day=60s&hot=weibo,douyin,zhihu # 在https://lytoday.lylme.com/code.html生成你的接口地址 填入这里

qweather: '<div class="rounded-circle weather"><div id="he-plugin-simple" style="display: contents;"></div><iframe scrolling="no" src="https://widget.tianqiapi.com/?style=te&skin=pitaya&color=FFFFFF&paddingtop=6" frameborder="0" width="200" height="24" allowtransparency="true"></iframe></div>' #顶部导航栏天气预报代码

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  foot: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格 注意单个代码不能有换行。
    Copyright © <a target="_blank" href="">樊笼</a>
    <script>var _hmt = _hmt || [];(function() {var hm = document.createElement("script");hm.src = "https://hm.baidu.com/hm.js?062685e39e06f9947b865df2e13901f7";var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hm, s);})();</script>

logo:
  iconlight: https://files.seeusercontent.com/2026/04/08/jo2D/logo.png
  icondark: https://files.seeusercontent.com/2026/04/08/jo2D/logo.png
  light: https://files.seeusercontent.com/2026/04/08/g0mD/logo-light.png
  dark: https://files.seeusercontent.com/2026/04/08/Aj2s/logo-dark.png

#网址分类 config值 对应在数据文件名称
menu:
  - name: 工作网址
    icon: fa fa-briefcase
    config: 01x
    submenu:
      - name: 金融证券
        icon: fa fa-chart-line
        config: 01x01
      - name: 企业查询
        icon: fa fa-building
        config: 01x02
      - name: 内部系统
        icon: fa fa-server
        config: 01x03
      - name: AI工具
        icon: fa fa-tools
        config: 01x04

  - name: 常用网址
    icon: fa fa-star
    config: 02x
    submenu:
      - name: 常用收藏
        icon: fa fa-heart
        config: 02x01
      - name: 我的网站
        icon: fa fa-tools
        config: 02x02
      - name: 编程工具
        icon: fa fa-tools
        config: 02x03

  - name: 常用工具
    icon: fa fa-cut
    config: 03x
    submenu:
      - name: 在线工具
        icon: fa fa-globe
        config: 03x01
      - name: 文档处理
        icon: fa fa-file-alt
        config: 03x02
      - name: 开发工具
        icon: fa fa-code
        config: 03x03

footmenu:
  # - name: 在线留言
  #   icon: fa fa-commenting-o
  #   url: https://kok.plus/comments/
  - name: 网站提交
    icon: fa fa-pencil
    url: https://f.kdocs.cn/ksform/w/write/ExrZwQ1Z/

headmenu:
  - name: 樊笼
    icon: fa fa-user-circle-o
    url: https://252262.xyz
  # - name: 本站源码
  #   icon: fa fa-file-code-o
  #   url: https://kok.plus/hexonav